# Generated by Django 4.2.5 on 2023-10-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.billingaddress'),
        ),
        migrations.AddField(
            model_name='account',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_link_id',
            field=models.UUIDField(default=None),
        ),
    ]
