# Generated by Django 4.2.5 on 2023-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_account_billing_account_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_link_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
