# Generated by Django 4.2.5 on 2023-10-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitems_sku_alter_shoppingbasket_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='imones pavadinimas')),
                ('address', models.CharField(max_length=200, verbose_name='imones addresas')),
                ('company_registration_code', models.CharField(max_length=20, verbose_name='imones kodas')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
    ]
