# Generated by Django 4.2.5 on 2024-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productprices',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlocation',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
