# Generated by Django 5.0.2 on 2024-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productimages_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='img/categories/default.png', upload_to='C:\\Users\\Audrius\\Documents\\vscode\\finalproject\\ecommerce\\shop/static/img/categories/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(upload_to='C:\\Users\\Audrius\\Documents\\vscode\\finalproject\\ecommerce\\shop/static/img/products/'),
        ),
    ]
