# Generated by Django 5.0.2 on 2024-03-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_category_picture_and_more'),
        ('shop', '0017_alter_productquantity_location_and_more'),
    ]

    operations = [
    ]
