# Generated by Django 4.2.5 on 2024-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_merge_20240316_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='img/categories/default.png', upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/categories/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/products/'),
        ),
    ]
