# Generated by Django 4.2.5 on 2024-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_category_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='img/categories/default.png', upload_to='C:\\pythonProjects\\finalproject\\ecommerce_project\\shop/static/img/categories/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(upload_to='C:\\pythonProjects\\finalproject\\ecommerce_project\\shop/static/img/products/'),
        ),
    ]
