# Generated by Django 4.2.5 on 2024-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_categories_alter_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
