# Generated by Django 4.2.5 on 2024-03-28 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(validators=[django.core.validators.MinValueValidator(5, message='Value is to short! required lenght 5 symbols')], verbose_name='Product status')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productstatus'),
        ),
    ]
