# Generated by Django 4.2.5 on 2024-03-28 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productstatus_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name': 'Product status', 'verbose_name_plural': 'Product statuses'},
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(5, message='Value is to short! required lenght 5 symbols')]),
        ),
    ]
