# Generated by Django 4.2.5 on 2024-03-28 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_productstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, message='Value is to short! required lenght 5 symbols')]),
        ),
    ]
