# Generated by Django 4.2.5 on 2024-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AV', 'Product is available to buy'), ('AOS', 'Product is out of stock'), ('SOUT', 'Product is sold out'), ('DMG', 'Product is damaged or package is damaged'), ('ST1', 'Example status 1'), ('ST2', 'Example status 2'), ('ST3', 'Example status 3')], default='AV', max_length=4),
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
    ]
