# Generated by Django 5.0.2 on 2024-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_status_delete_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='img/categories/default.png', upload_to='C:\\Users\\Audrius\\Documents\\vscode\\finalproject\\ecommerce_project\\shop/static/img/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('AOS', 'Product is out of stock'), ('SOUT', 'Product is sold out'), ('DMG', 'Product is damaged or package is damaged'), ('ST1', 'Example status 1'), ('ST2', 'Example status 2'), ('ST3', 'Example status 3')], default='AV', max_length=4),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(upload_to='C:\\Users\\Audrius\\Documents\\vscode\\finalproject\\ecommerce_project\\shop/static/img/products/'),
        ),
    ]
