# Generated by Django 5.0.2 on 2024-03-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_category_picture_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(max_length=1000, upload_to='C:\\Users\\Audrius\\Documents\\vscode\\finalproject\\ecommerce_project\\shop/static/img/products/'),
        ),
    ]
