# Generated by Django 4.2.5 on 2024-04-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_category_products_alter_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productquantity',
            options={'verbose_name_plural': 'Product quantities'},
        ),
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='shop.category')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='shop.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(through='shop.CategoryParent', to='shop.category'),
        ),
    ]
