# Generated by Django 4.2.5 on 2024-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_category_options_alter_productquantity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
