# Generated by Django 4.2.5 on 2024-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_category_related_categories'),
    ]

    operations = [

    ]
