# Generated by Django 4.2.5 on 2024-04-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_category_related_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related_categories',
        ),
    ]
