# Generated by Django 4.2.5 on 2024-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_remove_category_related_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(blank=True, to='shop.category'),
        ),
    ]
