# Generated by Django 4.2.5 on 2024-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_category_related_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='shop.category'),
        ),
    ]
