# Generated by Django 4.2.5 on 2023-09-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productquantity_product_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(default='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/products//default_no_img.jpg', upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/products/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
        ),
    ]
