# Generated by Django 4.2.5 on 2023-10-09 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customuser_unique_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.account'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('paid_at_Date', models.DateField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.billingaddress')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.deliveryaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
