# Generated by Django 4.2.5 on 2023-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimages_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_name',
            field=models.ImageField(upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/products/'),
        ),
    ]
