# Generated by Django 4.2.5 on 2023-10-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customuser_account_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbasket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.billingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.deliveryaddress'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=1000)),
                ('price', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
