# Generated by Django 4.2.5 on 2023-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimages_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/categories/'),
        ),
    ]
