# Generated by Django 4.2.5 on 2023-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='categories/default.png', upload_to='C:\\pythonProjects\\finalproject\\ecommerce\\shop/static/img/categories/'),
        ),
    ]
