# Generated by Django 4.2.5 on 2023-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
