# Generated by Django 4.2.5 on 2024-02-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productquantity_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='date_created',
        ),
    ]
