# Generated by Django 5.0.2 on 2024-03-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='type',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('MAIN', 'Main')], default='SIMPLE', max_length=10),
        ),
        migrations.AddField(
            model_name='productprices',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='productlocation',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='productprices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='shop.productlocation'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='shop.product'),
        ),
    ]
