# Generated by Django 5.0.2 on 2024-03-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productimages_type_productprices_date_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='shop.productlocation'),
        ),
    ]
