# Generated by Django 4.2.5 on 2023-10-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shoppingbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbasket',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
