# Generated by Django 4.2.5 on 2024-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productprices_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='type',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('MAIN', 'Main')], default='SIMPLE', max_length=10),
        ),
    ]
