# Generated by Django 4.2.5 on 2024-03-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productquantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='location_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
