# Generated by Django 4.2.5 on 2024-03-12 16:59

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_productlocation_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='location_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productquantity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('product'), django.db.models.functions.text.Lower('location'), name='unique_product_location'),
        ),
    ]
