# Generated by Django 4.2.5 on 2024-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productlocation_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='location_name',
            field=models.CharField(max_length=250),
        ),
    ]
